// <auto-generated />
namespace Vidzy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _4thIteration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4thIteration));
        
        string IMigrationMetadata.Id
        {
            get { return "202207251804119_4thIteration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
